### ISSUE TITLE
Failing "go get -u github.com/ThreeDotsLabs/watermill" on Windows

### ISSUE THREAD

**Issue by marcofranssen** [ThreeDotsLabs/watermill#60]
Following fails on my Windows. It looks like watermill is having some exotic external dependencies which do not work out of the box on Windows, neither it is documented bzr is required.

This makes it hard to get a working environment on at least Windows to use watermill. Would be great if this could be simplyfied. Or maybe some of external deps to be internalized.

```bash
$ go get -u github.com/ThreeDotsLabs/watermill                                                                                        go: finding github.com/armon/go-metrics latest                                                                                        go: finding github.com/streadway/amqp latest                                                                                          go: finding github.com/pascaldekloe/goe latest                                                                                        go: finding golang.org/x/net latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/oauth2 latest
go: finding github.com/eapache/go-xerial-snappy latest
go: finding golang.org/x/crypto latest
go: finding github.com/google/btree latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/lint latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/build latest
go: finding github.com/shurcooL/gopherjslib latest
go: labix.org/v2/mgo@v0.0.0-20140701140051-000000000287: bzr branch --use-existing-dir https://launchpad.net/mgo/v2 . in C:\private-s tuff\go-workspace\pkg\mod\cache\vcs\ca61c737a32b1e09a0919e15375f9c2b6aa09860cc097f1333b3c3d29e040ea8: exit status 4:
    bzr: ERROR: httplib.IncompleteRead: IncompleteRead(34 bytes read)

    Traceback (most recent call last):
         File "bzrlib\commands.pyo", line 920, in exception_to_return_code
         File "bzrlib\commands.pyo", line 1131, in run_bzr
         File "bzrlib\commands.pyo", line 673, in run_argv_aliases
         File "bzrlib\commands.pyo", line 695, in run
         File "bzrlib\cleanup.pyo", line 136, in run_simple
         File "bzrlib\cleanup.pyo", line 166, in _do_with_cleanups
         File "bzrlib\builtins.pyo", line 1438, in run
         File "bzrlib\controldir.pyo", line 779, in open_tree_or_branch
         File "bzrlib\controldir.pyo", line 459, in _get_tree_branch
         File "bzrlib\bzrdir.pyo", line 1082, in open_branch
         File "bzrlib\branch.pyo", line 2375, in open
         File "bzrlib\controldir.pyo", line 687, in open
         File "bzrlib\controldir.pyo", line 716, in open_from_transport
         File "bzrlib\transport\__init__.pyo", line 1718, in do_catching_redirections
         File "bzrlib\controldir.pyo", line 704, in find_format
         File "bzrlib\controldir.pyo", line 1149, in find_format
         File "C:/Program Files (x86)/Bazaar/plugins\git\__init__.py", line 235, in probe_transport
         File "C:/Program Files (x86)/Bazaar/plugins\git\__init__.py", line 182, in probe_http_transport
         File "socket.pyo", line 348, in read
         File "httplib.pyo", line 522, in read
         File "httplib.pyo", line 565, in _read_chunked
    IncompleteRead: IncompleteRead(34 bytes read)

    bzr 2.5.1 on python 2.6.6 (Windows-post2008Server-6.2.9200)
    arguments: ['bzr', 'branch', '--use-existing-dir',
        'https://launchpad.net/mgo/v2', '.']
    plugins: bzrtools[2.5.0], changelog_merge[2.5.1], colo[0.4.0],
        explorer[1.2.2], fastimport[0.14.0dev], git[0.6.8], launchpad[2.5.1],
        loom[2.3.0dev], netrc_credential_store[2.5.1], news_merge[2.5.1],
        pipeline[1.4.0], qbzr[0.22.3], rewrite[0.6.4dev], svn[1.2.2],
        upload[1.2.0dev], xmloutput[0.8.8]
    encoding: 'cp1252', fsenc: 'mbcs', lang: 'en_US.UTF-8'

    *** Bazaar has encountered an internal error.  This probably indicates a
          bug in Bazaar.  You can help us fix it by filing a bug report at
              https://bugs.launchpad.net/bzr/+filebug
          including this traceback and a description of the problem.
go: finding grpc.go4.org latest
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: golang.org/x/net@v0.0.0-20190108225652-1e06a53dbb7e: unknown revision 1e06a53dbb7e
go: finding github.com/shurcooL/github_flavored_markdown latest
go: finding github.com/shurcooL/httpgzip latest
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/t runk . in C:\private-stuff\go-workspace\pkg\mod\cache\vcs\f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exit stat us 4:
    bzr: ERROR: httplib.IncompleteRead: IncompleteRead(34 bytes read)

    Traceback (most recent call last):
         File "bzrlib\commands.pyo", line 920, in exception_to_return_code
         File "bzrlib\commands.pyo", line 1131, in run_bzr
         File "bzrlib\commands.pyo", line 673, in run_argv_aliases
         File "bzrlib\commands.pyo", line 695, in run
         File "bzrlib\cleanup.pyo", line 136, in run_simple
         File "bzrlib\cleanup.pyo", line 166, in _do_with_cleanups
         File "bzrlib\builtins.pyo", line 1438, in run
         File "bzrlib\controldir.pyo", line 779, in open_tree_or_branch
         File "bzrlib\controldir.pyo", line 459, in _get_tree_branch
         File "bzrlib\bzrdir.pyo", line 1082, in open_branch
         File "bzrlib\branch.pyo", line 2375, in open
         File "bzrlib\controldir.pyo", line 687, in open
         File "bzrlib\controldir.pyo", line 716, in open_from_transport
         File "bzrlib\transport\__init__.pyo", line 1718, in do_catching_redirections
         File "bzrlib\controldir.pyo", line 704, in find_format
         File "bzrlib\controldir.pyo", line 1149, in find_format
         File "C:/Program Files (x86)/Bazaar/plugins\git\__init__.py", line 235, in probe_transport
         File "C:/Program Files (x86)/Bazaar/plugins\git\__init__.py", line 182, in probe_http_transport
         File "socket.pyo", line 348, in read
         File "httplib.pyo", line 522, in read
         File "httplib.pyo", line 565, in _read_chunked
     IncompleteRead: IncompleteRead(34 bytes read)

     bzr 2.5.1 on python 2.6.6 (Windows-post2008Server-6.2.9200)
     arguments: ['bzr', 'branch', '--use-existing-dir',
        'https://launchpad.net/~niemeyer/gocheck/trunk', '.']
    plugins: bzrtools[2.5.0], changelog_merge[2.5.1], colo[0.4.0],
        explorer[1.2.2], fastimport[0.14.0dev], git[0.6.8], launchpad[2.5.1],
        loom[2.3.0dev], netrc_credential_store[2.5.1], news_merge[2.5.1],
        pipeline[1.4.0], qbzr[0.22.3], rewrite[0.6.4dev], svn[1.2.2],
        upload[1.2.0dev], xmloutput[0.8.8]
    encoding: 'cp1252', fsenc: 'mbcs', lang: 'en_US.UTF-8'

    *** Bazaar has encountered an internal error.  This probably indicates a
          bug in Bazaar.  You can help us fix it by filing a bug report at
          https://bugs.launchpad.net/bzr/+filebug
          including this traceback and a description of the problem.
go get: error loading module requirements
```

**Comment by roblaszczak** [comment]
I did some go.mod cleanup on the master. Can you check `go get -u github.com/ThreeDotsLabs/watermill@master`?

Of course we will add these changes to the release, but it need a bit of testing but generally it should work fine :)

**Comment by marcofranssen** [comment]
Thanks Robert,

I will give it a shot tomorrow and let you know.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by marcofranssen** [comment]
Did give it a shot. Below the new error ;)

```bash
$ go get -u github.com/ThreeDotsLabs/watermill@master
go: finding github.com/ThreeDotsLabs/watermill master
go: finding google.golang.org/grpc v1.19.0
go: finding github.com/streadway/amqp latest
go: finding github.com/stretchr/objx v0.1.1
go: finding golang.org/x/time latest
go: finding golang.org/x/sync latest
go: finding github.com/google/btree latest
go: finding golang.org/x/oauth2 latest
go: finding go.opencensus.io v0.19.1
go: finding github.com/prometheus/procfs latest
go: finding github.com/kisielk/errcheck v1.1.0
go: finding github.com/eapache/go-xerial-snappy latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
go: finding honnef.co/go/tools latest
go: finding github.com/beorn7/perks latest
go: finding golang.org/x/build latest
go: finding github.com/sourcegraph/syntaxhighlight latest
go: finding github.com/prometheus/client_model latest
go: finding github.com/tarm/serial latest
go: finding github.com/shurcooL/highlight_diff latest
go: finding golang.org/x/tools latest
go: finding golang.org/x/lint latest
go: finding github.com/shurcooL/gofontwoff latest
go: finding github.com/kisielk/errcheck v1.2.0
go: finding github.com/prometheus/common v0.2.0
go: finding github.com/coreos/go-systemd latest
go: finding github.com/shurcooL/sanitized_anchor_name v1.0.0
go: finding github.com/shurcooL/gopherjslib latest
go: finding golang.org/x/tools v0.0.0-20180221164845-07fd8470d635
go: finding gopkg.in/check.v1 latest
go: finding github.com/golang/glog latest
go: finding github.com/shurcooL/highlight_go latest
go: finding github.com/googleapis/gax-go v2.0.2+incompatible
go: finding github.com/rcrowley/go-metrics latest
go: finding github.com/shurcooL/httpgzip latest
go: finding github.com/shurcooL/octicon latest
go: finding dmitri.shuralyov.com/app/changes latest
go: finding github.com/openzipkin/zipkin-go v0.1.5
go: finding honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099
go: finding github.com/shurcooL/htmlg latest
go: finding dmitri.shuralyov.com/state latest
go: finding github.com/grpc-ecosystem/grpc-gateway v1.8.1
go: finding github.com/shurcooL/httperror latest
go: finding github.com/shurcooL/events latest
go: finding grpc.go4.org latest
go: finding github.com/shurcooL/users latest
go: finding github.com/shurcooL/home latest
go: finding dmitri.shuralyov.com/service/change latest
go: finding github.com/shurcooL/issuesapp latest                                                                                      go: finding github.com/microcosm-cc/bluemonday v1.0.2
go: finding golang.org/x/sys latest
go: finding github.com/sourcegraph/annotate latest
go: finding go4.org latest
go: finding github.com/google/pprof latest
go: finding github.com/shurcooL/reactions latest
go: finding github.com/neelance/astrewrite latest
go: finding golang.org/x/tools v0.0.0-20190226205152-f727befe758c
go: finding github.com/shurcooL/webdavfs latest
go get: upgrading github.com/grpc-ecosystem/grpc-gateway@v1.5.0: git -c protocol.version=0 fetch --unshallow -f https://github.com/gr pc-ecosystem/grpc-gateway refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in C:\private-stuff\go-workspace\pkg\mod\cache\vcs\dbefe9 d952531da41030e8565a04a4b41c255a5f682a843c38d400f856098ce9: exit status 128:
fatal: Unable to create 'C:/private-stuff/go-workspace/pkg/mod/cache/vcs/dbefe9d952531da41030e8565a04a4b41c255a5f682a843c38d4 00f856098ce9/shallow.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
go: finding github.com/prometheus/client_golang v0.9.1
go: finding github.com/flynn/go-shlex latest
go: finding github.com/go-kit/kit v0.8.0
go: finding github.com/bradfitz/go-smtpd latest
go: finding github.com/jellevandenhooff/dkim latest
go: finding github.com/golang/lint latest
go: finding github.com/shurcooL/issues latest
go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
go: finding golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961
go: finding github.com/alecthomas/template latest
go: finding github.com/julienschmidt/httprouter v1.2.0
go: finding github.com/shurcooL/httpfs latest
go: finding golang.org/x/exp latest
go: finding github.com/shurcooL/github_flavored_markdown latest
go: finding github.com/alecthomas/units latest
go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: finding github.com/gliderlabs/ssh v0.1.3
go: golang.org/x/net@v0.0.0-20190213061140-3a22650c66bd: git -c protocol.version=0 fetch --unshallow -f https://go.googlesource.com/n et refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in C:\private-stuff\go-workspace\pkg\mod\cache\vcs\4a22365141bc4eea5d5ac4a1395e6 53f2669485db75ef119e7bbec8e19b12a21: exit status 128:
fatal: Unable to create 'C:/private-stuff/go-workspace/pkg/mod/cache/vcs/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bb ec8e19b12a21/shallow.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
go: finding golang.org/x/sys v0.0.0-20181116152217-5ac8a444bdc5
go: golang.org/x/net@v0.0.0-20190108225652-1e06a53dbb7e: unknown revision 1e06a53dbb7e
go: finding golang.org/x/net v0.0.0-20181201002055-351d144fa1fc
go: golang.org/x/net@v0.0.0-20181201002055-351d144fa1fc: unknown revision 351d144fa1fc
go: finding github.com/shurcooL/notifications latest
go: finding github.com/go-stack/stack v1.8.0
go: finding github.com/prometheus/procfs v0.0.0-20181005140218-185b4288413d
go: finding golang.org/x/tools v0.0.0-20181030221726-6c7e314b6563
go: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
go: finding golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
go: finding github.com/sirupsen/logrus v1.2.0
go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: finding github.com/go-logfmt/logfmt v0.3.0
go: finding github.com/russross/blackfriday v2.0.0+incompatible
go get: error loading module requirements
```

**Comment by roblaszczak** [comment]
Can you try to remove C:/private-stuff/go-workspace/pkg/mod/cache/vcs/
dbefe9d952531da41030e8565a04a4b41c255a5f682a843c38d4
00f856098ce9/shallow.lock? Looks like some git/Windows problem here.

**Comment by marcofranssen** [comment]
I cleared out my whole C:/private-stuff/go-workspace/pkg/mod/cache folder. I think this might be a bug with `go get` which leaves lock files around when `go get` is failing. `go get -u github.com/ThreeDotsLabs/watermill@master` took me more then 20 minutes. with all the deps to be downloaded. Not sure if that is related to only watermill or because of restoring the cache.

**Comment by roblaszczak** [comment]
@marcofranssen We will split Pub/Subs to separated repositories before v1.0 release, it may reduce dependencies size :)
